@echo off
REM Compile VR GLSL shaders to SPIR-V and generate C header files.
REM Requires Vulkan SDK installed with VULKAN_SDK environment variable set.
REM Skips compilation if the .spv.h output is newer than the source shader.

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
set "GLSLANG=%VULKAN_SDK%\Bin\glslangValidator.exe"

if not exist "%GLSLANG%" (
  echo ERROR: glslangValidator not found at %GLSLANG%
  echo Make sure VULKAN_SDK environment variable is set correctly.
  exit /b 1
)

REM --- Vertex shader ---
set "VERT_SRC=%SCRIPT_DIR%vr_shader.vert"
set "VERT_SPV=%SCRIPT_DIR%vr_shader_vert.spv"
set "VERT_HDR=%SCRIPT_DIR%vr_shader_vert.spv.h"

call :compile_shader "%VERT_SRC%" "%VERT_SPV%" "%VERT_HDR%" s_vr_vertex_shader_spirv
if errorlevel 1 exit /b 1

REM --- Fragment shader ---
set "FRAG_SRC=%SCRIPT_DIR%vr_shader.frag"
set "FRAG_SPV=%SCRIPT_DIR%vr_shader_frag.spv"
set "FRAG_HDR=%SCRIPT_DIR%vr_shader_frag.spv.h"

call :compile_shader "%FRAG_SRC%" "%FRAG_SPV%" "%FRAG_HDR%" s_vr_fragment_shader_spirv
if errorlevel 1 exit /b 1

echo Shader compilation complete.
exit /b 0

REM ============================================================
REM Subroutine: compile_shader <src> <spv> <hdr> <symbol_name>
REM ============================================================
:compile_shader
set "SRC=%~1"
set "SPV=%~2"
set "HDR=%~3"
set "SYM=%~4"

REM Check if header is newer than source (skip if up-to-date)
if exist "%HDR%" (
  powershell -NoProfile -Command "if ((Get-Item '%SRC%').LastWriteTime -le (Get-Item '%HDR%').LastWriteTime) { exit 0 } else { exit 1 }"
  if !errorlevel! EQU 0 (
    echo %SYM%: up-to-date, skipping.
    exit /b 0
  )
)

echo Compiling %SRC% ...
"%GLSLANG%" -V "%SRC%" -o "%SPV%"
if errorlevel 1 (
  echo ERROR: Failed to compile %SRC%
  exit /b 1
)

echo Generating %HDR% ...
powershell -NoProfile -Command ^
  "$bytes = [System.IO.File]::ReadAllBytes('%SPV%');" ^
  "$sb = [System.Text.StringBuilder]::new();" ^
  "$sb.AppendLine('// Auto-generated by compile_shaders.bat - do not edit') | Out-Null;" ^
  "$sb.AppendLine('// Source: ' + [System.IO.Path]::GetFileName('%SRC%')) | Out-Null;" ^
  "$sb.AppendLine('') | Out-Null;" ^
  "$sb.AppendLine('static const unsigned char %SYM%[] = {') | Out-Null;" ^
  "for ($i = 0; $i -lt $bytes.Length; $i += 12) {" ^
  "  $end = [Math]::Min($i + 12, $bytes.Length);" ^
  "  $line = '  ' + (($bytes[$i..($end-1)] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ');" ^
  "  if ($end -lt $bytes.Length) { $line += ',' };" ^
  "  $sb.AppendLine($line) | Out-Null;" ^
  "}" ^
  "$sb.AppendLine('};') | Out-Null;" ^
  "$sb.AppendLine('static const unsigned int %SYM%_len = ' + $bytes.Length + ';') | Out-Null;" ^
  "[System.IO.File]::WriteAllText('%HDR%', $sb.ToString());"

if errorlevel 1 (
  echo ERROR: Failed to generate %HDR%
  exit /b 1
)

exit /b 0
