# spv_to_header.cmake - Convert SPIR-V binary to C header file.
# Called by CMakeLists.txt with: -DSPV_FILE=... -DHDR_FILE=... -DSYM_NAME=...

file(READ "${SPV_FILE}" SPV_HEX HEX)
string(LENGTH "${SPV_HEX}" SPV_HEX_LEN)
math(EXPR SPV_BYTE_LEN "${SPV_HEX_LEN} / 2")

# Build comma-separated hex byte list with line wrapping
set(HEX_CONTENT "")
set(LINE "")
set(BYTES_ON_LINE 0)
math(EXPR LAST_BYTE "${SPV_BYTE_LEN} - 1")
foreach(BYTE_IDX RANGE 0 ${LAST_BYTE})
  math(EXPR HEX_IDX "${BYTE_IDX} * 2")
  string(SUBSTRING "${SPV_HEX}" ${HEX_IDX} 2 BYTE_HEX)
  if(BYTES_ON_LINE GREATER 0)
    string(APPEND LINE ", ")
  endif()
  string(APPEND LINE "0x${BYTE_HEX}")
  math(EXPR BYTES_ON_LINE "${BYTES_ON_LINE} + 1")
  if(BYTES_ON_LINE EQUAL 12 OR BYTE_IDX EQUAL ${LAST_BYTE})
    if(BYTE_IDX LESS ${LAST_BYTE})
      string(APPEND HEX_CONTENT "  ${LINE},\n")
    else()
      string(APPEND HEX_CONTENT "  ${LINE}\n")
    endif()
    set(LINE "")
    set(BYTES_ON_LINE 0)
  endif()
endforeach()

get_filename_component(SRC_NAME "${SPV_FILE}" NAME_WE)
string(REGEX REPLACE "_[^_]+$" "" SRC_BASE "${SRC_NAME}")
file(WRITE "${HDR_FILE}"
  "// Auto-generated by spv_to_header.cmake - do not edit\n"
  "// Source: ${SRC_NAME}\n"
  "\n"
  "static const unsigned char ${SYM_NAME}[] = {\n"
  "${HEX_CONTENT}"
  "};\n"
  "static const unsigned int ${SYM_NAME}_len = ${SPV_BYTE_LEN};\n"
)
